    .text
    .globl _start
_start:
    addi x1, x0, 10
    addi x2, x0, 20
    add x3, x1, x2
    sw x3, 0(x0)
    addi x1, x0, 11
    addi x2, x0, 21
    add x3, x1, x2
    sw x3, 4(x0)
    addi x1, x0, 12
    addi x2, x0, 22
    add x3, x1, x2
    sw x3, 8(x0)
    addi x1, x0, 13
    addi x2, x0, 23
    add x3, x1, x2
    sw x3, 12(x0)
    addi x1, x0, 14
    addi x2, x0, 24
    add x3, x1, x2
    sw x3, 16(x0)
    addi x1, x0, 15
    addi x2, x0, 25
    add x3, x1, x2
    sw x3, 20(x0)
    addi x1, x0, 16
    addi x2, x0, 26
    add x3, x1, x2
    sw x3, 24(x0)
    addi x1, x0, 17
    addi x2, x0, 27
    add x3, x1, x2
    sw x3, 28(x0)
    addi x1, x0, 18
    addi x2, x0, 28
    add x3, x1, x2
    sw x3, 32(x0)
    addi x1, x0, 19
    addi x2, x0, 29
    add x3, x1, x2
    sw x3, 36(x0)
    addi x1, x0, 20
    addi x2, x0, 30
    add x3, x1, x2
    sw x3, 40(x0)
    addi x1, x0, 21
    addi x2, x0, 31
    add x3, x1, x2
    sw x3, 44(x0)
    addi x1, x0, 22
    addi x2, x0, 32
    add x3, x1, x2
    sw x3, 48(x0)
    addi x1, x0, 23
    addi x2, x0, 33
    add x3, x1, x2
    sw x3, 52(x0)
    addi x1, x0, 24
    addi x2, x0, 34
    add x3, x1, x2
    sw x3, 56(x0)
    addi x1, x0, 25
    addi x2, x0, 35
    add x3, x1, x2
    sw x3, 60(x0)
    addi x1, x0, 26
    addi x2, x0, 36
    add x3, x1, x2
    sw x3, 64(x0)
    addi x1, x0, 27
    addi x2, x0, 37
    add x3, x1, x2
    sw x3, 68(x0)
    addi x1, x0, 28
    addi x2, x0, 38
    add x3, x1, x2
    sw x3, 72(x0)
    addi x1, x0, 29
    addi x2, x0, 39
    add x3, x1, x2
    sw x3, 76(x0)
    addi x1, x0, 30
    addi x2, x0, 40
    add x3, x1, x2
    sw x3, 80(x0)
    addi x1, x0, 31
    addi x2, x0, 41
    add x3, x1, x2
    sw x3, 84(x0)
    addi x1, x0, 32
    addi x2, x0, 42
    add x3, x1, x2
    sw x3, 88(x0)
    addi x1, x0, 33
    addi x2, x0, 43
    add x3, x1, x2
    sw x3, 92(x0)
    addi x1, x0, 34
    addi x2, x0, 44
    add x3, x1, x2
    sw x3, 96(x0)
    addi x1, x0, 35
    addi x2, x0, 45
    add x3, x1, x2
    sw x3, 100(x0)
    addi x1, x0, 36
    addi x2, x0, 46
    add x3, x1, x2
    sw x3, 104(x0)
    addi x1, x0, 37
    addi x2, x0, 47
    add x3, x1, x2
    sw x3, 108(x0)
    addi x1, x0, 38
    addi x2, x0, 48
    add x3, x1, x2
    sw x3, 112(x0)
    addi x1, x0, 39
    addi x2, x0, 49
    add x3, x1, x2
    sw x3, 116(x0)
